-- CreateEnum
CREATE TYPE "VerificationStatus" AS ENUM ('pending', 'approved', 'rejected');

-- CreateEnum
CREATE TYPE "ServiceCategory" AS ENUM ('NEW_CONNECTIONS', 'NETWORK_OPERATIONS', 'METERING_BILLING', 'CUSTOMER_SUPPORT');

-- CreateEnum
CREATE TYPE "ServiceType" AS ENUM ('NEW_RESIDENTIAL', 'COMMERCIAL_INDUSTRIAL', 'TEMPORARY_POWER', 'ACCESSIBILITY_INSTALL', 'CAPACITY_CHANGE', 'TRANSFORMER_REPAIR', 'SUBSTATION_INSPECTION', 'CABLE_REPAIR', 'TREE_TRIMMING', 'VOLTAGE_COMPLAINT', 'EMERGENCY_REPAIR', 'METER_MALFUNCTION', 'METER_REPLACEMENT', 'METER_READING', 'BILL_DISPUTE', 'PAYMENT_EXTENSION', 'DUPLICATE_BILL', 'OUTAGE_REPORT', 'VOLTAGE_FLUCTUATION', 'GENERAL_COMPLAINT', 'REQUEST_TRACKING', 'SERVICE_ESCALATION', 'INFO_UPDATE');

-- CreateTable
CREATE TABLE "ServiceApplication" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "serviceType" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "documents" TEXT[],
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ServiceApplication_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "ServiceApplication" ADD CONSTRAINT "ServiceApplication_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
